### PR TITLE
Improve test code reuse

### PR DESCRIPTION
**Pull request by khatchad**
Reuse some code.

### CODE REVIEW

**Comment by khatchad** [comment]
Hi @orenwf. Can you please review this?

**Comment by orenwf** [comment]
Hey, sorry for the delay. It looks like a couple of small changes, and I'm just going to add the lines in manually since there are large diffs of deleted / obsolete code which is a bit confusing to look at and merge.

**Comment by orenwf** [comment]
Actually on second thought, it's not that bad, I'm going to be able to merge it as normal.

**Comment by khatchad** [comment]
Merging now.

**Comment by khatchad** [comment]
I feel if this doesn't merge soon then the conflict resolution will be too difficult later.

**Comment by orenwf** [comment]
Thanks, no prob.

**Comment by khatchad** [comment]
Weird that the coverage dropped.

**Pull request merged**
